package(
    default_visibility = [
        "//polyflow:internal"
    ],
)

cc_library(
    name = "tf",
    hdrs = ["tf_runtime.h"],
    srcs = ["tf_runtime.cc"],
    deps = [
        "//polyflow/core:model_runtime",
    ],    
)
