package(
    default_visibility = [
        "//polyflow:internal"
    ],
)

cc_library(
    name = "tf",
    hdrs = ["tf_model_loader.h"],
    srcs = ["tf_model_loader.cc"],
    deps = [
        "//polyflow/core:model_loader",
    ],    
)
