package(
    default_visibility = [
        "//polyflow:internal"
    ],
)

cc_library(
    name = "ov",
    hdrs = ["ov_runtime.h"],
    srcs = ["ov_runtime.cc"],
    deps = [
        "//polyflow/core:model_runtime",
    ],    
)
