package(
    default_visibility = [
        "//polyflow:internal"
    ],
)

cc_library(
    name = "trt",
    hdrs = ["trt_runtime.h"],
    srcs = ["trt_runtime.cc"],
    deps = [
        "//polyflow/core:model_runtime",
    ],    
)
