package(
    default_visibility = [
        "//polyflow:internal"
    ],
)

cc_library(
    name = "trt",
    hdrs = ["trt_model_loader.h"],
    srcs = ["trt_model_loader.cc"],
    deps = [
        "//polyflow/core:model_loader",
    ],    
)
